name: Deploy to Lightsail
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run script with secret
        env:
          MY_SECRET: ${{ secrets.USERNAME }}
        run: |
          # use the secret in your script
          echo $MY_SECRET
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y golang
      - run: echo ${{ secrets.HOST }}
      - run: echo "::debug::Debug mode on"
      - run: echo ${{ secrets.USERNAME }}
      - run: echo ${{ secrets.PRIVATE_KEY }}
      - name: Build application
        run: go build -o app
      - name: Deploy to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: ./app
          target: /home/ubuntu/myapp/
      - name: SSH into Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/myapp
            sudo systemctl stop myapp
            mv app myapp
            sudo systemctl start myapp
